# Generated by Django 5.1.6 on 2025-09-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_users_created_at_remove_users_is_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
