# Generated by Django 5.2.6 on 2025-09-08 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transaction_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESP32Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.station')),
            ],
        ),
    ]
