# Generated by Django 5.1.6 on 2025-09-11 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transactions_method_transactions_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanrecord',
            name='station_id',
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='station',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.station'),
            preserve_default=False,
        ),
    ]
