# Generated by Django 5.2.6 on 2025-09-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_scanrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='card_uid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
