# Generated by Django 5.2.6 on 2025-09-10 12:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_esp32status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user_password', models.CharField(max_length=255)),
                ('is_student', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='esp32status',
            name='current_station',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fraudlog',
            name='user',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='status',
            new_name='ticket_status',
        ),
        migrations.RemoveField(
            model_name='fraudlog',
            name='detected_at',
        ),
        migrations.RemoveField(
            model_name='fraudlog',
            name='handled',
        ),
        migrations.AddField(
            model_name='fraudlog',
            name='detected_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='card_uid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.station'),
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ticket'),
        ),
        migrations.AlterField(
            model_name='fraudlog',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='end_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_station', to='api.station'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_station', to='api.station'),
        ),
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_uid', models.CharField(max_length=50)),
                ('station', models.CharField(max_length=100)),
                ('scan_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ticket')),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transactions'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.DeleteModel(
            name='DeviceConfig',
        ),
        migrations.DeleteModel(
            name='ESP32Status',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
