# Generated by Django 5.1.6 on 2025-09-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_scanrecord_station_id_scanrecord_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_check_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_station_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_station_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
