# Generated by Django 5.2.6 on 2025-09-12 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ticket_last_check_time_ticket_last_station_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
