# Generated by Django 5.2.6 on 2025-09-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transactions_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanrecord',
            name='ticket',
        ),
        migrations.AddField(
            model_name='users',
            name='card_uid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
