# Generated by Django 5.2.6 on 2025-09-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transactions_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='card_uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
