# Generated by Django 5.2.6 on 2025-09-11 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_scanrecord_ticket_users_card_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecord',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ticket'),
        ),
    ]
