# Generated by Django 5.2.6 on 2025-09-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_scanrecord_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
