# Generated by Django 5.2.6 on 2025-09-11 04:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_station_station_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanrecord',
            name='id',
        ),
        migrations.RemoveField(
            model_name='scanrecord',
            name='scan_time',
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='error_reason',
            field=models.CharField(choices=[('NoTicket', 'NoTicket'), ('Expired', 'Expired'), ('Blocked', 'Blocked'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='scan_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='ticket_found',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.users'),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='card_uid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.station'),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ticket'),
        ),
    ]
