# Generated by Django 5.2.6 on 2025-09-11 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_scanrecord_id_remove_scanrecord_scan_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationAssignment',
            fields=[
                ('device_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('CheckIn', 'CheckIn'), ('CheckOut', 'CheckOut')], max_length=20)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.station')),
            ],
        ),
    ]
