# Generated by Django 5.2.6 on 2025-09-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_stationassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationassignment',
            name='device_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
