# Generated by Django 5.2.6 on 2025-09-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_stationassignment_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanrecord',
            name='station',
        ),
        migrations.RemoveField(
            model_name='scanrecord',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='scanrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='device_type',
            field=models.CharField(blank=True, choices=[('CheckIn', 'CheckIn'), ('CheckOut', 'CheckOut')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='station_id',
            field=models.CharField(default='UNKNOWN', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='card_uid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='error_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
