# Generated by Django 5.2.6 on 2025-09-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_scanrecord_station_remove_scanrecord_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecord',
            name='device_id',
            field=models.CharField(default='UNKNOWN', max_length=10),
        ),
    ]
