# Generated by Django 5.2.6 on 2025-09-11 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_scanrecord_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudlog',
            name='card_uid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fraudlog',
            name='station_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fraudlog',
            name='user',
            field=models.ForeignKey(default='25a208a1256c475bbc155a8592ab3fc2', on_delete=django.db.models.deletion.CASCADE, to='api.users'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='fraudlog',
            index=models.Index(fields=['ticket'], name='api_fraudlo_ticket__386ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudlog',
            index=models.Index(fields=['user'], name='api_fraudlo_user_id_ebb5ff_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudlog',
            index=models.Index(fields=['detected_time'], name='api_fraudlo_detecte_65840c_idx'),
        ),
    ]
